In [50]:
import numpy as np
import pandas as pd

In [51]:
df = pd.read_excel("FuelConsumptionCo2.xlsx")
df.head()

,MODELYEAR,MAKE,MODEL,VEHICLECLASS,ENGINESIZE,CYLINDERS,TRANSMISSION,FUELTYPE,FUELCONSUMPTION_CITY,FUELCONSUMPTION_HWY,FUELCONSUMPTION_COMB,FUELCONSUMPTION_COMB_MPG,CO2EMISSIONS
0,2022,Acura,ILX,Compact,2.4,4,AM8,Z,9.9,7.0,8.6,33,200
1,2022,Acura,MDX SH-AWD,SUV: Small,3.5,6,AS10,Z,12.6,9.4,11.2,25,263
2,2022,Acura,RDX SH-AWD,SUV: Small,2.0,4,AS10,Z,11.0,8.6,9.9,29,232
3,2022,Acura,RDX SH-AWD A-SPEC,SUV: Small,2.0,4,AS10,Z,11.3,9.1,10.3,27,242
4,2022,Acura,TLX SH-AWD,Compact,2.0,4,AS10,Z,11.2,8.0,9.8,29,230

In [52]:
#Remover caracteristicas categoricas
df.drop(['MODELYEAR', 'MAKE', 'MODEL', 'VEHICLECLASS', 'TRANSMISSION', 'FUELTYPE'], axis=1, inplace=True)
df

,ENGINESIZE,CYLINDERS,FUELCONSUMPTION_CITY,FUELCONSUMPTION_HWY,FUELCONSUMPTION_COMB,FUELCONSUMPTION_COMB_MPG,CO2EMISSIONS
0,2.4,4,9.9,7.0,8.6,33,200
1,3.5,6,12.6,9.4,11.2,25,263
2,2.0,4,11.0,8.6,9.9,29,232
3,2.0,4,11.3,9.1,10.3,27,242
4,2.0,4,11.2,8.0,9.8,29,230
...,...,...,...,...,...,...,...
940,2.0,4,10.7,7.7,9.4,30,219
941,2.0,4,10.5,8.1,9.4,30,219
942,2.0,4,11.0,8.7,9.9,29,232
943,2.0,4,11.5,8.4,10.1,28,236
944,2.0,4,12.4,8.9,10.8,26,252

In [53]:
#Remover renglones con valores faltantes
df.dropna(inplace=True)
df

,ENGINESIZE,CYLINDERS,FUELCONSUMPTION_CITY,FUELCONSUMPTION_HWY,FUELCONSUMPTION_COMB,FUELCONSUMPTION_COMB_MPG,CO2EMISSIONS
0,2.4,4,9.9,7.0,8.6,33,200
1,3.5,6,12.6,9.4,11.2,25,263
2,2.0,4,11.0,8.6,9.9,29,232
3,2.0,4,11.3,9.1,10.3,27,242
4,2.0,4,11.2,8.0,9.8,29,230
...,...,...,...,...,...,...,...
940,2.0,4,10.7,7.7,9.4,30,219
941,2.0,4,10.5,8.1,9.4,30,219
942,2.0,4,11.0,8.7,9.9,29,232
943,2.0,4,11.5,8.4,10.1,28,236
944,2.0,4,12.4,8.9,10.8,26,252

In [54]:
X = df.drop('CO2EMISSIONS', axis=1)
y = df['CO2EMISSIONS']

In [55]:
# Division en grupos de entrenamiento(training) y de prueba(testing)
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [56]:
#Normalizacion
from sklearn.preprocessing import normalize
X_train_norm = normalize(X_train)
X_test_norm = normalize(X_test)

# Regresion lineal multiple

In [62]:
# Construccion de un modelo de regresion lineal multiple
from sklearn.linear_model import LinearRegression
linreg = LinearRegression()
linreg.fit(X_train_norm, y_train)

LinearRegression()

In [63]:
# Coeficientes de regresion
print('Intercepto: ', linreg.intercept_)
print('Coeficientes: ', linreg.coef_)

Intercepto:  388.74250128235667
Coeficientes:  [-116.50352944  111.94245879  -28.55294687  -57.30206895  329.02984369
 -281.56796432]

In [81]:
valores_x = X.iloc[0]

intercepto = linreg.intercept_
coeficientes = linreg.coef_

In [82]:
# Pronostico de la primera observación de la base de prueba
y_pronosticada = intercepto + sum(coeficientes * valores_x)
y_pronosticada

np.float64(-6588.970957818888)

In [12]:
# Predicciones
y_pred = linreg.predict(X_test_norm)
y_pred

array([242.05056484, 313.42558914, 313.48838497, 250.08779357,
       268.74965249, 210.50834944, 268.07050854, 175.86564657,
       255.97184449, 292.29252653, 132.45443294, 266.48524379,
       243.4632638 , 200.16986777, 263.77265219, 209.23127096,
       282.57265984, 203.26463198, 185.12727518, 300.69297149,
       335.3267567 , 183.6514229 , 377.36202361, 339.22374611,
       268.07050854, 217.69173134, 356.57217613, 360.97835427,
       167.01216892, 333.3653351 , 305.26219156, 239.96354809,
       286.50756304, 237.21125781, 211.02897624, 192.64050467,
       176.39865173, 365.80530797, 359.12417466, 235.32432818,
       231.90736269, 292.76633292, 331.63311108, 168.44837239,
       264.57589623, 209.47811931, 232.04193336, 334.8798269 ,
       358.74392968, 289.9084445 , 161.61005512, 230.51763281,
       297.47314749, 281.5914438 , 419.08030717, 215.21763864,
       177.07211043, 301.38928609, 167.25332091, 321.89888714,
       435.86929512, 291.52669948, 224.32122829, 139.18159019,
       255.27219161, 309.41715428, 181.28538375, 328.12608316,
       198.67552655, 330.44828829, 183.483367  , 264.72877856,
       207.97522482, 244.310262  , 330.02074674, 192.5088289 ,
       226.06810099, 216.40015521, 278.39322697, 216.26886518,
       233.53710673, 218.91283216, 225.15729506, 277.95862935,
       256.63943434, 257.82824849, 358.94659495, 202.84147863,
       175.41847901, 269.92701684, 239.14793897, 244.4183101 ,
       291.31427346, 257.2453337 , 265.87470196, 328.61675383,
       287.94434141, 217.54556443, 306.66996839, 258.64277828,
       286.50756304, 231.91973568, 169.71054603, 242.35356765,
       335.32001469, 445.15874798, 218.35654252, 181.71797119,
       203.32171423, 145.05111005, 217.29709627, 210.07134669,
       273.08571623, 199.34097778, 159.60072616, 348.08206562,
       230.82089366, 387.07034654, 320.24079344, 257.48558096,
       255.27219161, 277.75204582, 247.80520538, 217.56353583,
       269.03517184, 398.20755815, 349.06189426, 233.9137383 ,
       195.76551059, 204.6067269 , 330.41271546, 159.61488596,
       190.88714727, 395.97404331, 187.78828031, 358.94659495,
       226.6444936 , 222.93341779, 283.89280617, 266.23673307,
       212.1143844 , 264.34950465, 307.2164567 , 191.86064534,
       204.905297  , 224.92625149, 278.43864001, 162.41752887,
       410.34407169, 285.64110626, 249.6487248 , 286.50756304,
       218.25921454, 258.93597027, 277.62635982, 303.86904341,
       215.73884478, 289.0598286 , 284.62302774, 297.44781737,
       204.67003321, 233.9137383 , 241.18856033, 349.60287228,
       303.14350717, 200.16986777, 242.03068755, 318.23690912,
       223.20409297, 357.87784666, 229.8966387 , 246.43890797,
       435.86929512, 258.51498493, 189.73552653, 305.91656292,
       316.37482423, 216.50738612, 306.65905638, 168.09040168,
       215.96522398, 211.47129096, 175.41847901, 268.62640333,
       247.91787169, 140.76656537, 217.19586233, 203.55851004,
       286.50756304, 277.06602518, 248.13229103, 215.3283669 ,
       245.74598196, 252.07196924, 225.32201632, 254.53009283,
       226.82989433, 333.3653351 , 159.73191524, 291.64307492,
       232.28544307, 226.1967093 , 259.04309365, 168.09351213,
       214.45554765, 162.31488882, 290.97726269, 282.10144595,
       191.33556758, 274.249621  , 328.6169897 , 255.27219161,
       157.56381788, 240.27464325, 323.70808047, 203.49548517,
       302.65629279, 278.55613313, 311.32905323, 314.71901731,
       176.25392482, 266.16368874, 293.50062851, 245.29219719,
       393.01753901, 320.61384572, 228.92020239, 335.66204555,
       262.99498818, 222.20058047, 203.09180453, 178.08000041,
       344.00706647, 343.08631963, 211.41952163, 214.31979801,
       171.68208044, 221.22116572, 146.61513039, 229.8966387 ,
       349.60287228, 281.09740261, 266.02278361, 317.69746694,
       187.63616134, 221.09798918, 174.21319017, 283.18708977,
       182.93259492, 211.41952163, 266.02278361, 331.63311108,
       254.23256578, 142.68519761, 257.45136026, 287.92615041,
       167.85373411, 209.94400818, 305.84807985, 186.3107076 ,
       239.71613227, 278.08117158, 266.58567017, 259.71434619,
       198.02378947, 331.63311108, 276.42944377, 186.20756131,
       178.60709153, 233.85964144, 178.72760666, 167.07131963,
       210.921244  , 192.41472688, 159.42152062, 235.80126517,
       332.58716024, 262.24791379, 332.58716024, 226.77472848,
       270.16401494, 346.9169396 , 286.50756304, 240.17337864])

In [13]:
# Calculo de indicadores de la bondad de ajuste
from sklearn.metrics import r2_score
from sklearn import metrics

In [14]:
# Impresion de indicadores de la bondad de ajuste
print('Valor de R2: ', r2_score(y_test, y_pred))
print('Error absoluto medio: ', metrics.mean_absolute_error(y_test, y_pred))
print('Error cuadratico medio: ', metrics.mean_squared_error(y_test, y_pred))
print('Raiz del error cuadratico medio: ', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))

Valor de R2:  0.9101041999638888
Error absoluto medio:  7.582278595997424
Error cuadratico medio:  311.19797055029375
Raiz del error cuadratico medio:  17.64080413559126

# Ridge

In [15]:
alpha_range = 10.**np.arange(-2, 3)
alpha_range

array([1.e-02, 1.e-01, 1.e+00, 1.e+01, 1.e+02])

In [16]:
from sklearn.linear_model import RidgeCV

ridgeregcv = RidgeCV(alphas=alpha_range, scoring='neg_mean_squared_error')
ridgeregcv.fit(X_train_norm, y_train)
ridgeregcv.alpha_

np.float64(0.1)

In [17]:
# Coeficientes de regresion
print('Intercepto: ', ridgeregcv.intercept_)
print('Coeficientes: ', ridgeregcv.coef_)

Intercepto:  370.62064522979716
Coeficientes:  [ -49.94511915   80.3014429   109.58287072   59.01305057   89.25870857
 -265.36368388]

In [69]:
intercepto = ridgeregcv.intercept_
coeficientes = ridgeregcv.coef_

In [70]:
# Pronostico de la primera observación de la base de prueba
y_pronosticada = intercepto + sum(coeficientes * valores_x)
y_pronosticada

np.float64(-5919.456769450476)

In [71]:
# Predicciones
y_pred = ridgeregcv.predict(X_test_norm)
y_pred

array([243.207916  , 313.14677668, 313.30423144, 250.29296954,
       269.35640365, 210.53248917, 266.44635094, 174.8715644 ,
       255.53956093, 291.1147997 , 131.24617184, 267.12125888,
       243.14749014, 199.28852065, 263.68197064, 208.81457041,
       281.95624325, 202.82287569, 186.25508733, 299.55623607,
       333.81389069, 183.5172903 , 374.52335181, 337.66202676,
       266.44635094, 218.15425036, 355.309407  , 359.64350816,
       166.99834338, 332.44405976, 308.59479151, 240.54143366,
       286.20885598, 236.89118883, 211.45942985, 192.56240732,
       175.39938295, 364.00087486, 360.73786118, 235.46170731,
       233.00383266, 295.1336707 , 332.4642764 , 168.18564129,
       267.67368098, 209.17817347, 232.32445771, 333.5250365 ,
       358.73818421, 289.45652358, 161.60120363, 230.23803067,
       296.545695  , 281.04954218, 418.00548984, 216.18184696,
       177.616426  , 301.14026616, 167.06918565, 319.95604688,
       433.19823889, 290.72767885, 224.22889951, 139.43659034,
       255.70006419, 310.2687047 , 180.62344542, 327.15236698,
       198.22102012, 331.58265462, 183.58824873, 264.37229498,
       208.62850194, 244.35296828, 331.30683864, 191.90816069,
       226.45614713, 216.52544377, 277.78978154, 216.14853579,
       233.37678191, 218.72334235, 226.26225288, 277.35477638,
       257.66855005, 258.33258535, 359.32005161, 202.85386118,
       175.10872905, 269.55861751, 238.81908992, 245.66267431,
       290.23277754, 256.86576385, 265.21080233, 331.15678618,
       287.97463795, 217.23848023, 307.36998215, 257.69321032,
       286.20885598, 232.14326031, 169.5930584 , 242.5743255 ,
       333.23648676, 440.53575168, 218.2572365 , 181.66939931,
       204.51215392, 145.27281891, 216.87146709, 209.38113217,
       273.56591064, 198.35328271, 160.11021259, 349.81795342,
       231.66379382, 383.43341257, 320.46099535, 258.22897128,
       255.70006419, 278.82367255, 248.20892424, 217.9675466 ,
       268.96115006, 396.00621574, 350.81648686, 233.93639042,
       197.11046993, 204.45509674, 330.31867832, 160.4329901 ,
       190.79658378, 394.04661702, 187.11657535, 359.32005161,
       226.39843981, 223.71955943, 285.28234664, 266.76886869,
       210.89597656, 264.38216777, 307.65892142, 193.46370429,
       205.24010247, 225.42538971, 279.45697678, 161.71095081,
       408.09745705, 285.45071048, 249.74933117, 286.20885598,
       218.80902165, 258.63467612, 277.22553085, 302.67985985,
       216.60507686, 289.05227746, 283.97024345, 296.69298156,
       204.89039429, 233.93639042, 241.41737375, 349.68998816,
       301.74235155, 199.28852065, 242.45013693, 319.30391196,
       223.01219533, 359.54362313, 229.85725954, 246.7270252 ,
       433.19823889, 258.18714859, 190.6124297 , 307.15145774,
       316.30263436, 216.58556259, 308.09016038, 167.17945981,
       216.13222927, 211.43922657, 175.10872905, 269.19139796,
       247.65143194, 139.50834317, 217.4223127 , 204.09023972,
       286.20885598, 277.25220284, 248.40339912, 215.263152  ,
       246.70482244, 252.55642219, 226.1592758 , 255.30936763,
       227.03433262, 332.44405976, 160.34097471, 290.90748541,
       231.97420438, 226.64410284, 258.23636275, 167.92302644,
       214.82048663, 161.25067651, 290.09950152, 282.19672276,
       191.1361551 , 275.80028429, 331.11558842, 255.70006419,
       157.81671273, 240.28089152, 321.92632915, 203.65479612,
       301.42237385, 277.85221262, 310.04429839, 314.95112096,
       175.48316828, 267.01854746, 294.76116994, 244.85117736,
       391.39538208, 321.0047831 , 228.94132331, 334.40982926,
       264.15406882, 223.27419654, 204.16761928, 178.26317391,
       344.14634557, 345.00247604, 211.70712743, 215.37788136,
       170.86801685, 221.8712061 , 146.88717876, 229.85725954,
       349.68998816, 281.51476716, 265.18335464, 318.85663178,
       187.66679859, 221.28695994, 174.35012341, 281.78429141,
       183.05893205, 211.70712743, 265.18335464, 332.4642764 ,
       254.10208163, 142.02549699, 256.79044863, 289.19097161,
       167.8532553 , 209.99265115, 306.52992342, 186.46432576,
       240.19207208, 277.81297934, 266.06752558, 259.03842669,
       198.36166478, 332.4642764 , 277.03530796, 187.39693388,
       178.42712228, 234.21752172, 178.76063729, 166.78697772,
       211.29229868, 192.22570162, 159.0156989 , 235.78083718,
       333.78077309, 264.48690963, 333.78077309, 227.41700579,
       270.07704742, 347.47683776, 286.20885598, 241.31859723])

In [20]:
# Impresion de indicadores de la bondad de ajuste
print('Valor de R2: ', r2_score(y_test, y_pred))
print('Error absoluto medio: ', metrics.mean_absolute_error(y_test, y_pred))
print('Error cuadratico medio: ', metrics.mean_squared_error(y_test, y_pred))
print('Raiz del error cuadratico medio: ', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))

Valor de R2:  0.9127388477539915
Error absoluto medio:  7.450651668123023
Error cuadratico medio:  302.07744383975273
Raiz del error cuadratico medio:  17.38037525025719

# Lasso

In [21]:
from sklearn.linear_model import LassoCV

lassoregcv = LassoCV(n_alphas=100, random_state=1)
lassoregcv.fit(X_train_norm, y_train)
print('Alpha optimo: ', lassoregcv.alpha_)

Alpha optimo:  0.085544800184034

In [22]:
# Coeficientes de regresion
print('Intercepto: ', lassoregcv.intercept_)
print('Coeficientes: ', lassoregcv.coef_)

Intercepto:  424.31751626979326
Coeficientes:  [   0.            0.          137.92132714    0.           63.04551538
 -305.26713558]

In [72]:
intercepto = lassoregcv.intercept_
coeficientes = lassoregcv.coef_

In [73]:
# Pronostico de la primera observación de la base de prueba
y_pronosticada = intercepto + sum(coeficientes * valores_x)
y_pronosticada

np.float64(-7741.885387043674)

In [74]:
# Prediccion con Alpha optimo
y_pred = lassoregcv.predict(X_test_norm)
y_pred

array([244.2242231 , 310.6909983 , 309.39998916, 249.46182267,
       268.26866578, 211.59162365, 263.37296674, 175.60497434,
       253.56028493, 289.43435264, 136.94387132, 266.03381349,
       243.78672994, 199.49666249, 262.14280384, 209.53396852,
       280.40602104, 201.8903316 , 187.96147316, 298.49678733,
       331.45290308, 186.00591311, 372.89346857, 336.01221889,
       263.37296674, 219.29391693, 353.27698103, 358.20149887,
       169.57711783, 331.4564989 , 312.22965224, 241.292069  ,
       283.30734907, 233.56814795, 211.16886664, 194.39391631,
       176.66591643, 364.09645911, 365.86765931, 236.43642546,
       235.85304174, 296.03356702, 331.57509548, 170.65387117,
       266.6354503 , 210.42175783, 230.19235036, 330.17131673,
       358.38380026, 287.47805309, 165.21837433, 227.19371841,
       294.211036  , 279.78001071, 425.98987798, 215.89426522,
       180.71786506, 300.50500293, 170.19669739, 319.05733349,
       438.46167237, 287.33748116, 225.95399895, 144.96899386,
       253.99137776, 308.84245829, 181.90758148, 326.20756146,
       198.24406747, 330.24937916, 185.71279342, 262.20684618,
       209.82117525, 246.70335674, 329.00288018, 192.61232117,
       227.01079013, 214.63741923, 274.33521368, 214.30984401,
       232.9952806 , 220.09670223, 226.49539581, 274.58177704,
       254.73865638, 258.04777286, 357.69455122, 204.30692764,
       177.81501266, 267.43328426, 237.69132612, 244.1712331 ,
       287.93644915, 255.16499774, 262.51338047, 335.50494523,
       286.11926626, 218.11735866, 306.58418063, 253.93273739,
       283.30734907, 229.74314509, 173.5121602 , 243.41939644,
       328.33014924, 450.11213908, 218.42837114, 181.88333799,
       206.21404003, 148.77934455, 217.21694647, 207.65215064,
       271.72734661, 197.46700047, 162.19295704, 354.93973745,
       231.26913035, 383.04078731, 320.65686022, 256.37407207,
       253.99137776, 275.99677699, 244.88989519, 218.83981243,
       265.73228034, 401.80072763, 356.24421441, 234.38284771,
       198.58466539, 205.03894848, 331.15928576, 162.59822848,
       192.30382215, 399.0812342 , 187.93707948, 357.69455122,
       225.70956843, 224.15197528, 284.15681268, 264.23473187,
       210.53282839, 260.92546513, 305.73219169, 195.06622231,
       206.45383012, 226.88367388, 279.07777636, 164.44513628,
       413.37297547, 281.74030806, 250.17264565, 283.30734907,
       218.71195561, 255.65608954, 274.62495333, 302.01145808,
       216.77247201, 288.10514818, 283.33474152, 295.46053615,
       205.59469627, 234.38284771, 242.28380189, 349.89085383,
       301.7865436 , 199.49666249, 243.45882451, 317.75115768,
       220.56072214, 365.97380968, 227.91397434, 242.8667927 ,
       438.46167237, 256.76499671, 192.11236828, 307.09989212,
       313.56667365, 217.63655657, 305.34107759, 169.38440905,
       215.98106985, 212.19165019, 177.81501266, 266.9495592 ,
       244.5938447 , 143.46955993, 217.4969494 , 204.71064939,
       283.30734907, 275.37055704, 247.54611034, 213.72410542,
       245.61135458, 253.10385701, 226.79424538, 252.79416345,
       226.7480353 , 331.4564989 , 162.82232485, 287.80576321,
       230.37843735, 227.4706163 , 257.07032659, 170.97521277,
       213.71030259, 163.69750151, 287.97600233, 279.12217711,
       191.99368107, 274.65818351, 331.56600971, 253.99137776,
       160.50002063, 239.00220884, 318.51179146, 204.15486908,
       300.43115489, 276.38577495, 310.8293248 , 313.28196766,
       176.40409836, 265.2258647 , 293.68209237, 240.98543788,
       395.61384264, 322.08698784, 227.29942907, 335.11200966,
       262.13704468, 221.84535298, 205.36226871, 179.98488511,
       343.52252755, 346.63758519, 212.32484624, 215.74117772,
       172.2378543 , 221.43798793, 150.13216581, 227.91397434,
       349.89085383, 281.99637439, 260.09128783, 316.04455397,
       188.9782356 , 219.03396114, 176.42983797, 278.85792809,
       183.89640239, 212.32484624, 260.09128783, 331.57509548,
       254.14511683, 146.04914524, 255.51331471, 289.40460235,
       170.35764517, 209.29157301, 303.87654675, 186.99922712,
       239.07310137, 273.75602548, 262.38439112, 257.74365435,
       198.55759859, 331.57509548, 274.62316321, 189.27661754,
       181.31845307, 234.52742624, 179.73830609, 169.48839618,
       210.74525388, 193.56820742, 159.91370855, 237.73256435,
       333.09518162, 262.55870408, 333.09518162, 223.32725668,
       266.85659094, 347.71697805, 283.30734907, 243.40981077])

In [25]:
# Impresion de indicadores de la bondad de ajuste
print('Valor de R2: ', r2_score(y_test, y_pred))
print('Error absoluto medio: ', metrics.mean_absolute_error(y_test, y_pred))
print('Error cuadratico medio: ', metrics.mean_squared_error(y_test, y_pred))
print('Raiz del error cuadratico medio: ', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))

Valor de R2:  0.9067951896584938
Error absoluto medio:  7.453202795795379
Error cuadratico medio:  322.65298058585995
Raiz del error cuadratico medio:  17.962543822795812